platform:ios, ‘8.0’
target "Capp" do
pod 'AFNetworking', '~> 3.0.4'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 0.6.4'
pod 'SDCycleScrollView', '~> 1.3'
pod 'MJRefresh'
pod 'MBProgressHUD','~> 0.9.2'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/Sina'
end